#pragma once

#define NAMESPACE_FLUENTX FluentX
#define NAMESPACE_USING_FLUENTX namespace NAMESPACE_FLUENTX

#define FLUENTX_DEBUG					1

#define FLUENTX_ENABLE_RUNTIME_ERRORS		0
#define FLUENTX_ENABLE_MSGBOX_ERRORS		1
#define FLUENTX_ENABLE_CODE_LOCATION_ERROR	1